version: "3.8"

services:
  webtools_web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn webtools.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    ports:
      - 8000:8000
    depends_on:
      - webtools_db
    environment:
      PYTHONPATH: /usr/src/webtools

  webtools_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
