# Generated by Django 5.0.1 on 2024-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='key',
            field=models.CharField(max_length=100000, unique=True, verbose_name='key'),
        ),
    ]
